spring.datasource.url=jdbc:mysql://localhost:3306/intellidocs_ai
spring.datasource.username=root
spring.datasource.password=Jyothika@*21

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=8080
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB

groq.api.key=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